[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'kassio/neoterm'
